services:
  - type: web
    name: libraflow-backend
    env: node
    plan: free
    buildCommand: npm ci && cd server && npm ci
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.18.0